### ISSUE TITLE
Competitive just returns null

### ISSUE THREAD

**Issue by RustyRin** [TeKrop/overfast-api#11]
Expected return:
A competitive rank and tier
```
{
  "summary" : { ... },
  "endorsement": { ... },
  "competitive": {
    "pc": {
      "tank": {
        "division": "diamond",
        "tier": 3,
        ... ... ...
```
As expected from [doc](https://overfast-api.tekrop.fr/#tag/Players/operation/get_player_career_players__player_id__get)

What is returned:
Null
```
{
  "summary": {
    "competitive": null
```
I looked at the career profile site, it seems they removed the rank icon from peoples pages. 
So idk if that is what  broke it, or if its more from the response structure changing.

**Comment by TeKrop** [comment]
Thank you for reporting the issue, I'll take a look this week-end and keep you updated 😉

**Comment by TeKrop** [comment]
I took a look at several profile pages, and as you said they removed the rank icons from peoples pages :/ 
So we'll have to wait for a fix from them, I'll keep this issue listed here until they fix it.
If they take too much time to fix it, I'll temporarily remove the `competitive` field and I'll update the documentation accordingly

**Comment by TeKrop** [comment]
@RustyRin The issue has been fixed in the last update, is it OK for you ?
