### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by koyomitan3** [TeKrop/overfast-api#142]
Can't even do a simple player request

```
import requests


player_id = "name-number"
x = requests.get(f'https://overfast-api.tekrop.fr/players/{player_id}/summary')
print(x.status_code)
``` 

Always 404

**Comment by TeKrop** [comment]
Hello,

It's specified in the specs / documentation : when a player doesn't exist, the API returns an HTTP 404 response. You can also see the message in response body.

![Screenshot_2024-06-17-18-29-48-33_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/TeKrop/overfast-api/assets/6080933/b11c3009-84bc-4926-b50d-6d3cb757fc26)

Let me know if it's working fine for you 👍

**Comment by koyomitan3** [comment]
The player is literally me, with a public open profile for anyone to see everything, what do you mean?

**Comment by TeKrop** [comment]
Hmm, did you check the letter case (capital letters)? It could explain the issue 🤔
Can you try to search your profile on Blizzard pages, and then if you can consult your page, just copy-paste the Battle tag in the URL 👍 (with a - instead of #) 
https://overwatch.blizzard.com/en-us/search/?q=Name-number

**Comment by MatthewSH** [comment]
If possible could you also provide the Bnet ID?

**Comment by TeKrop** [comment]
@koyomitan3 Are you still encountering an issue? 🤔

**Comment by TeKrop** [comment]
I'm closing the issue as it's been two weeks without any news. Feel free to reopen it with additional information if you have any 👍
