### ISSUE TITLE
API does not support special characters

### ISSUE THREAD

**Issue by OskarD** [TeKrop/overfast-api#199]
**Describe the bug**
Player names like these return status code 400:
* 環地平弧#3519
* [ПАСУЛЯ#1474](https://overfast-api.tekrop.fr/players/%D0%9F%D0%90%D0%A1%D0%A3%D0%9B%D0%AF-1474)
* [Немо#21207](https://overfast-api.tekrop.fr/players/%D0%9D%D0%B5%D0%BC%D0%BE-21207)
* [#2211](https://overfast-api.tekrop.fr/players/%D2%85%D2%89%D2%87%D2%87%D2%87%D2%87%D2%89-2211) (This name doesn't even work in GitHub apparently, but it works in the game)
* [Némesis#21732](https://overfast-api.tekrop.fr/players/N%C3%A9mesis-21732)
* [FunkMëMommy#2867](https://overfast-api.tekrop.fr/players/FunkM%C3%ABMommy-2867)
* [Chérie#11430](https://overfast-api.tekrop.fr/players/Ch%C3%A9rie-11430)
* [byuǃ#2931](https://overfast-api.tekrop.fr/players/byu%C7%83-2931)

**To Reproduce**
Click on one of the links

**Expected behavior**
Player profile

**Comment by TeKrop** [comment]
Hello ! 

Thank you for the report. Unfortunately, the API is using official Blizzard pages for data, and it seems the users can't be found on these. You can try yourself here : https://overwatch.blizzard.com/en_US/search/

I tried all the names you shared, and [FunkMëMommy#2867](https://overfast-api.tekrop.fr/players/FunkM%C3%ABMommy-2867) is actually the only one working for me 😅 

Let me know if I can help you on anything else 👍

**Comment by OskarD** [comment]
Does the `players/{player_id}` endpoints do a search to find the profile, then get the information from the profile? I thought it somehow fetched it directly based on the battletag alone

**Comment by TeKrop** [comment]
Not directly, but it uses it to gather data about the last time a profile was updated, and the player namecard (which is not on the profile page).

I also noticed that if a profile can't be found in Blizzard search, it's not available if we try to use the url directly. 

Are the profiles you're trying to use public ? If that's the case, I'm afraid I can't do anything to help on this issue 😕

**Comment by OskarD** [comment]
I don't know if they're public, I just know that I get that error back so I assume the API doesn't know yet

**Comment by TeKrop** [comment]
If profiles can't be found on Blizzard pages, the API won't be able to resolve them 😕
It can happen for private profiles, or sometimes for some public profiles for some reason. It's not related to special char issue, I already had this feedback a few months ago.

**Comment by OskarD** [comment]
Oh, weird! Thanks anyway :)
