### ISSUE TITLE
[Suggestion] Add Portrait value to heroes/{hero_key} endpoint

### ISSUE THREAD

**Issue by Electrocute4u** [TeKrop/overfast-api#2]
I'm not sure if this was overlooked, but the **Portrait** value for a hero is only available on **/heroes** endpoint and not on the **heroes/{hero_key}** endpoint, which I find odd. It might just be a simple overlook from your part and nothing beyond that. And its also fairly simple to workaround this and obtain it either way. But as I noticed that you accept contributions/suggestions I decided to pass on my thoughts about this matter. 

As I build a Discord bot, its not hard to fetch the portrait from the  **/heroes** endpoint matching the key value with whatever hero and add that to the new object (could use index too, but you never know when the index order might change). But, looking at it from a resource-intensive perspective, it is one API call too much for a single portrait value, so it would be nice to find it where it should originally belong. 
### Thanks for reading this suggestion!

**Comment by TeKrop** [comment]
Hi !

Thank you for your suggestion 👍 It's a good one, I didn't think about it before as I'm still using my old system (one Blizzard page parsed = one endpoint on my side), and the portraits are not displayed on specific hero pages (example : https://overwatch.blizzard.com/en-us/heroes/ana/). 

I'll update it in order to be more flexible, and keep you updated here 😉

**Comment by TeKrop** [comment]
@Electrocute4u The refactoring of my old system is done, I'll more flexible in the future if I need to add some specific data 👍 
I also added the `portrait` attribute as you asked, don't hesitate to tell me if this is OK for you 😄

**Comment by Electrocute4u** [comment]
Appreciate it. 😄
It'll make life easier for people to find all the needed values for a hero on its own endpoint. 
Thanks for the swift update, looking forward to career and profile search once Blizzard sorts out their so far bug "free" game. 👍
