### ISSUE TITLE
After Mystery Heroes release, API endpoints are not giving out new data

### ISSUE THREAD

**Issue by roger-payload** [TeKrop/overfast-api#21]
Seems like stats for all heroes are frozen after Mystery Heroes was released (i.e time_played is really easy to see).
I am guessing this is on blizzards side, and not something in the API, but I figured I might post it.

**Comment by TeKrop** [comment]
Good call to post it, I actually didn't notice anything, so thank you for the feedback. I'll investigate and keep you updated here 😉

**Comment by roger-payload** [comment]
Just to add: even the player summary is static. Avatar, Namecard and Title is not updated.

**Comment by TeKrop** [comment]
For avatar, namecard and title, did you check if they were updated on career pages on Blizzard side ? I'll check on my side, but do you have examples of players affected by the issue ?

**Comment by TeKrop** [comment]
@roger-payload I seem to not having any issue regarding avatar, namecard and title, they're beeing updated properly. Are you still encountering an issue ?

**Comment by roger-payload** [comment]
Yes, I should probably have mentioned I have a console profile, and that didn't work properly until season 3.
Example account: TankTop-2148
Ingame namecard:
![image](https://user-images.githubusercontent.com/8613813/225837771-8ac00b12-de25-4da4-906b-79029a21c1b7.png)

The namecard that is returned in JSON:
https://d15f34w2p8l1cc.cloudfront.net/overwatch/30fe8830dd2510798d214d09737d26e0577b1763087c174e40b2595114db0d56.png

Also worth mentioning is that Reinhardt has 25 game wins when viewing stats in-game, but 22 in the API.
And the stats reflected in the API is the same as Blizzards own career profile search.
https://overwatch.blizzard.com/en-us/career/TankTop-2148/

So I'm guessing this is on Blizzards side then.

**Comment by roger-payload** [comment]
FYI, seems like the rest of the profiles I'm querying have started to update.
I probably just need to log in and out again of the game client to post the new data. Closing this.
