### ISSUE TITLE
Will the API be able to pull stats from seasons?

### ISSUE THREAD

**Issue by roger-payload** [TeKrop/overfast-api#30]
New season now, will it be possible to query specific seasons, or only all competitive history as one big bulk?

**Comment by TeKrop** [comment]
Well, as I'm only retrieving the data from Blizzard pages without any history between retrievals, you won't be able to query a specific season at the moment, as Blizzard doesn't expose data as such.

**Comment by roger-payload** [comment]
Does your API reflect the same as career pages from Blizzard?
i.e https://overwatch.blizzard.com/en-us/career/TankTop-2148/
I noticed that all stats are updated after sesason 4 began, **except** for the entire "games" section, like games played, games won etc.
Meaning for career data json objects:
`object > stats > console > competitive > career_stats > all-heroes > [2] > stats`
This seems to not have updated since yesterday, for any of the players I'm pulling stats for.

Maybe signs pointing to them flushing the stats for the new season? Do you know if they did this for previous seasons?

**Comment by roger-payload** [comment]
I use that section to make daily reports about my clans games, how many we played, lost, won etc, so it quickly becomes clear to me when it's not reflecting the truth.

**Comment by TeKrop** [comment]
Yes it does reflect the same as career pages from Blizzard, like the link you provided 👍

**Comment by TeKrop** [comment]
@roger-payload As far as I can remember, competitive stats shown on the Blizzard pages only reflect current season 🤔

May I help you on something else regarding this topic ?

**Comment by roger-payload** [comment]
Yeah, no, this is probably just some more console pleb issues, the Blizzard pages aren't updating either. It will all resolve when small indie game company Blizzard manages to update the stats for the new season.
So no need to keep this open, the API is doing what it should - thanks mate.
