### ISSUE TITLE
[Proposal]: Expose actual numbers of games won\loss in stats summary endpoint

### ISSUE THREAD

**Issue by ProgressoRU** [TeKrop/overfast-api#41]
Is there any reason why only winrate percentage is shown in the summary endpoint?

I feel like showing actual number of games won\loss along with winrate percentage is fairly common practice for progress tracking and as this values is already used to calculate winrate I think it would only be fair to expose them in the final response.

**Comment by TeKrop** [comment]
Fair point, when designing the endpoint I was thinking only the winrate would be used to track progress 🤔 But I agree and I can definitely add wins and losses in the endpoint, I'll keep you updated 😄

**Comment by TeKrop** [comment]
I did some checks, and in the meantime you can always use both `games_played` and `winrate` together, in order to find out the games won and lost

**Comment by TeKrop** [comment]
@ProgressoRU I updated the endpoint, `games_won` and `games_lost` are now exposed, don't hesitate to reach me if you encounter any other issue 😉
