### ISSUE TITLE
[Feature Request]: Expose season number for competitive stats

### ISSUE THREAD

**Issue by ProgressoRU** [TeKrop/overfast-api#47]
I mentioned this briefly in my previous issue. From the profile page it is possible to know from which competitive season stats on the page are. `blz-section.competitive-view` block contains 2 data atribbutes: `data-latestherostatrankseason` and `data-latestherostatrankseasonow2` which contains last season of OW1 and OW2 player has played respectively. I suggest to expose this data into API as it could be used in multiple useful ways. For example, to filter old \ irrelevant data or to track when player started to play new season.

**Comment by TeKrop** [comment]
Oh you're right, I totally forgot about it when you previously mentioned it. It could indeed be interesting to have this data in the API, to track whenever a player started to play in a new season for example like you said.

I'll work on it and keep you updated 😉

**Comment by TeKrop** [comment]
@ProgressoRU I'm working on it and I'm not sure exposing data about the last OW1 season is relevant and would be useful 🤔  What do you think ? Do you need it on your side ? I'll expose OW2 latest season played by the player in any case 😉

**Comment by TeKrop** [comment]
The last OW2 season is now available on the API ! 😄 https://overfast-api.tekrop.fr/#tag/Players/operation/get_player_summary_players__player_id__summary_get

**Comment by ProgressoRU** [comment]
I think OW2 season would be enough, thank you!
