### ISSUE TITLE
[bugfix] Adding Sourcery to the project

### ISSUE THREAD

**Issue by s-rigaud** [TeKrop/overfast-api#60]
Adding [Sourcery ](https://sourcery.ai/) to explore and fix minor bugfixes in the projects might be a good thing to have. I only tested a few files but I found the following errors, not sure all of them are right, I let you decide 😄 

- Type for `value` in `update_parser_cache` is `dict | list`
- Type for `parser_data` in `test_update_and_get_parser_cache` is `list[dict[str, str]]`
- ......

**Comment by TeKrop** [comment]
Good suggestion, trying it right away with automated scan and refacto PR for OSS projects 😄 The resulting PR is interesting, thank you for the suggestion 😃 I'll also install it on my IDE for future changes 😛

**Comment by s-rigaud** [comment]
You might also want to check the VS Code integration (or maybe Sublime Text one depending of what you are using). It really helps with some minor issues not raised in the generic generated PR 😊
