### ISSUE TITLE
PlayerData didn’t get updated

### ISSUE THREAD

**Issue by Backxtar** [TeKrop/overfast-api#65]
https://overfast-api.tekrop.fr/players/Backxtar-2493/summary

The playerdata didn’t get updated since 5 days…
I’m gold 2 in tank (ranked).

Maybe an issue? Or is Blizzard down?

**Comment by TeKrop** [comment]
Hello ! API data is based on data from Blizzard profile pages, and as you can see, your tank rank still isn't displayed on it, so it's more a Blizzard issue : https://overwatch.blizzard.com/en-us/career/Backxtar-2493/

**Comment by TeKrop** [comment]
I'm closing this issue as it seems to be Blizzard related. 
Let me know if I can help you in another way or if you spot another issue 👍
