### ISSUE TITLE
Missing heroes (Junkrat and Torbjorn)

### ISSUE THREAD

**Issue by PeraDev7** [TeKrop/overfast-api#66]
Hello,
i found that torbjon and junkrat are missing.
Why?

**Comment by TeKrop** [comment]
Hello, I'm retrieving the data from Blizzard pages, and it seems they are not here anymore 😅 Will have to wait for Blizzard to fix it.
https://overwatch.blizzard.com/en-us/heroes/

**Comment by GGuppyGit** [comment]
https://overwatch.blizzard.com/en-us/heroes/
https://overwatch.blizzard.com/en-us/career/GGuppy-1953/

Both characters appear in both of those links for me. but still not pulling stats for them.

**Comment by PeraDev7** [comment]
U have private profile.
You need to open the profile privacy

**Comment by GGuppyGit** [comment]
My profile was public at the time, had to private it for separate reasons.

Here's another example:
https://overwatch.blizzard.com/en-us/career/DaddyRod-11680/
https://overfast-api.tekrop.fr/players/DaddyRod-11680

Here is the snippet I'm having issues with. Junkrat and Torbjorn are both missing.
  ```
"stats": {
    "pc": {
      "quickplay": {
        "heroes_comparisons": {
          "time_played": {
            "label": "Time Played",
            "values": [
              {
                "hero": "reinhardt",
                "value": 98315
              },
              {
                "hero": "ana",
                "value": 64319
              },
              {
                "hero": "hanzo",
                "value": 59831
              },
              {
                "hero": "genji",
                "value": 59670
              },
```

**Comment by TeKrop** [comment]
@GGuppyGit On your example, both heroes are not displayed at all on Blizzard page, is it also the case for you ? As the API is based on those pages, that's why they're both missing.
![image](https://github.com/TeKrop/overfast-api/assets/6080933/7860be9f-b02b-4a43-b96d-fe5b1f8f88c8)

**Comment by GGuppyGit** [comment]
They appear for me. 
![image](https://github.com/TeKrop/overfast-api/assets/11550648/9c6335c0-dd2d-42af-94e6-ab75ba828b13)
![image](https://github.com/TeKrop/overfast-api/assets/11550648/a685b282-d233-4f17-ae21-1822c4cedc25)

**Comment by TeKrop** [comment]
OK I investigated a bit more, and I found out why : it seems linked to the user location for some reason 🤦 

I'm located in France, and so are my servers hosting the API, and Junkrat and Torbjorn are not displayed at all, either on the profile page or the heroes page.
I tried loading both pages with a VPN located in US, and they both appeared on the profile page and the heroes pages...

**Comment by PeraDev7** [comment]
wow, nice job blizzard!

**Comment by TeKrop** [comment]
I left a bug report on their forum as a last resort, hoping they will notice and fix this x) 
https://us.forums.blizzard.com/en/overwatch/t/junkrat-and-torbjorn-missing-on-heroes-page-and-career-page/849903

**Comment by GGuppyGit** [comment]
Seems to be fixed one way or another

**Comment by TeKrop** [comment]
Indeed they're back on Blizzard pages for me, and back on the API 😄 IDK if they saw my post on their forum but good timing, I'm closing the issue then 👍
