### ISSUE TITLE
[Question] Way to get top 500 standings?

### ISSUE THREAD

**Issue by benschlegel** [TeKrop/overfast-api#77]
Haven't found anything in the docs and im not sure if blizzard even exposes this, but it would be cool if you could get a players top 500 standing or the global top 500 leaderboard for each region, is there a way to do this?

**Comment by TeKrop** [comment]
Hello ! Thank you for the interest in the API. Sadly, I don't know any source exposing the top 500 standing, it doesn't seem that Blizzard exposes this data :/
