### ISSUE TITLE
Support for new competirive rank Ultimate

### ISSUE THREAD

**Issue by ProgressoRU** [TeKrop/overfast-api#94]
Currentley if you'll try to request a plyayer who achieved Champion rank API will crush with an error:
` ValueError: 'ultimate' is not a valid CompetitiveDivision`
Example: https://overfast-api.tekrop.fr/players/FDGod-2444/summary

**Comment by TeKrop** [comment]
Thank you for reporting it ! 
I fixed it and now it's working as expected 👍 
The rank is available as `ultimate` even they called it "Champion" in the game 🙈
